 # -*- coding: utf-8 -*-
{
    'name': 'Education Financial Management',
    'version': '19.0.1.0.0',
    'summary': 'Eduction Financial Management',
    'category': 'Education',
    'sequence': -329,
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['education_core','account'],
    'data': [
        'security/ir.model.access.csv',
        'views/education_fee_installment_view.xml',
        'views/education_fee_plan_view.xml',
        'views/education_fee_invoice_view.xml',
        'views/education_fee_penalty_rule_view.xml',
        'views/education_refund_request_views.xml',
        'views/account_move_reversal_view.xml',
        # 'views/account_followup_line_views.xml',
        'wizard/education_refund_reject_wizard_view.xml',
        'wizard/education_fee_summary_wizard_view.xml',
        'wizard/education_invoice_summary_wizard.xml',
        'report/ir_actions_report.xml',
        'report/education_fee_summary_report.xml',
        'report/education_invoice_summary_report.xml',
        'wizard/education_refund_summary_wizard.xml',
        'report/education_refund_summary_report.xml',
        'views/menu.xml',
    ],
    'assets' : {
            'web.assets_backend': [
                'education_financial_management/static/src/js/action_manager.js',
                                   ],
        },
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}