# -*- coding: utf-8 -*-
{
    'name': 'Education Attendance',
    'version': '19.0.1.0.0',
    'summary': 'Manage student and faculty attendance integrated with timetable',
    'category': 'Education',
    'sequence': -333,
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['education_core','mail','base','web'],
    'data': [
        'security/ir.model.access.csv',
        'views/res_partner_view.xml',
        'views/education_leave_request_view.xml',
        'views/education_attendance_view.xml',
        'views/education_attendance_line_view.xml',
        'views/education_attendance_summary.xml',
        'wizard/attendance_summary_wizard.xml',
        'wizard/student_report_wizard.xml',
        'report/ir_actions_report.xml',
        'report/attendance_report.xml',
        'views/res_config_settings_view.xml',
        'data/mail_template.xml',
        'data/cron.xml',
        'views/menu.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'education_attendances/static/src/css/custom.css',
            # 'education_attendances/static/src/js/action_manager.js',
        ],
    },

    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}