 # -*- coding: utf-8 -*-
{
    'name': 'Education Hostel Management',
    'version': '19.0.1.0.0',
    'summary': 'Manage Hostel Details',
    'category': 'Education',
    'sequence': -333,
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['base', 'mail','education_core'],
    'data': [
        'security/education_hostel_groups.xml',
        'security/ir.model.access.csv',
        'data/ir.sequence_data.xml',
        'views/education_hostel_views.xml',
        'views/education_hostel_application_views.xml',
        'views/education_hostel_room_views.xml',
        'views/education_hostel_floor_views.xml',
        'views/education_hostel_food_item_views.xml',
        'views/education_hostel_mess_views.xml',
        'views/res_partner_views.xml',
    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}