# -*- coding: utf-8 -*-
{
    'name': 'Education Core',
    'version': '1.0',
    'summary': 'Manage educational details and student data',
    'category': 'Education',
    'sequence': -333,
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['base', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/education_student_student_views.xml',
        'views/education_class_views.xml',
        'views/education_category_views.xml',
        'data/ir_sequence_data.xml',
        'views/education_enrollment_views.xml',
		'views/education_academic_year_views.xml',
		'views/education_session_views.xml',
        'views/education_program_views.xml',
        'views/education_course_views.xml',
        'views/education_scholarship_views.xml',
        'views/education_scholarship_criteria_views.xml',
        'views/education_document_view.xml',
        'views/education_class_room_view.xml',
        'views/menus.xml',
],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}