 # -*- coding: utf-8 -*-
{
    'name': 'Education Core',
    'version': '19.0.1.0.0',
    'summary': 'Manage educational details and student data',
    'category': 'Education',
    'sequence': -333,
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['base', 'mail','base_automation','hr'],
    'data': [
        'security/education_security_groups.xml',
        'security/ir.model.access.csv',
        'security/res_partner_security.xml',
        'security/hr_employee_security.xml',
        'security/education_enrollment_security.xml',
        'views/education_application.xml',
        'views/education_class_views.xml',
        'views/education_category_views.xml',
        'views/res_partner_view.xml',
        'views/hr_employee.xml',
        'data/ir_sequence_data.xml',
        'views/education_enrollment_views.xml',
		'views/education_academic_year_views.xml',
		'views/education_session_views.xml',
        'views/education_program_views.xml',
        'views/education_course_views.xml',
        'views/education_document_view.xml',
        'views/education_class_room_view.xml',
        'views/education_timetable_line_view.xml',
        'wizard/eduaction_application_reject_wizard.xml',
        'views/menus.xml',
],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}