# -*- coding: utf-8 -*-
{
    'name': 'Education Core',
    'version': '19.0.1.0.0',
    'summary': 'Manage educational details and student data',
    'category': 'Education',
    'sequence': -333,
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['base', 'mail','base_automation'],
    'data': [
        'data/education_student_student_data.xml',
        'data/education_class_room_data.xml',
        'data/education_academic_year_data.xml',
        'data/education_program_data.xml',
        'data/education_class_data.xml',
        'data/education_course_data.xml',
        'data/education_session_data.xml',
        'data/education_scholarship_criteria_data.xml',
        'data/education_scholarship_data.xml',
        'data/ir_action_data.xml',
        'security/education_security_groups.xml',
        'security/ir.model.access.csv',
        'views/education_student_student_views.xml',
        'views/education_class_views.xml',
        'views/education_category_views.xml',
        'data/ir_sequence_data.xml',
        'views/education_enrollment_views.xml',
		'views/education_academic_year_views.xml',
		'views/education_session_views.xml',
        'views/education_program_views.xml',
        'views/education_course_views.xml',
        'views/education_scholarship_views.xml',
        'views/education_scholarship_criteria_views.xml',
        'views/education_document_view.xml',
        'views/education_class_room_view.xml',
        'views/menus.xml',
],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}