# -*- coding: utf-8 -*-
{
    'name': 'Education Mobile & Portal Access',
    'version': '19.0.1.0.0',
    'category': 'Education',
    'sequence': -327,
    'description': '''Manage portal and mobile access''',
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['base', 'mail','website','education_core' ,'portal',
                'education_exam','education_hostel_management','education_attendances'],
    'data': [
        'views/education_application_template.xml',
        'views/education_hostel_application_template.xml',
        'views/portal.xml',
        'views/education_library_template.xml',
        'views/education_library_book_template.xml',
        'views/education_library_myhistory.xml',
        'views/education_exam_template.xml',
        'views/education_exam_published_template.xml',
        'views/education_exam_result_template.xml',
        'views/education_exam_revaluation_application.xml',
        'views/education_leave_template.xml',
        'views/education_leave_form_template.xml',
        'views/education_leave_history.xml',
        'views/education_attendance.xml',

        'views/education_hostel_template.xml',
        'views/education_scholarship_template.xml',
        'views/education_scholarship_published.xml',
        'views/education_scholarship_application.xml',
        'views/education_scholarship_details.xml',
        'views/education_transport.xml',
        'views/education_student_profile_template.xml',
        'views/education_student_profile.xml',
        'views/education_student_document.xml',

        'views/education_menu.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'education_mobile_and_portal_access/static/src/js/education_attendance.js',
        ],
    },

    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}