from . import education_fee_plan
from . import education_fee_installment
from . import education_fee_invoice
from . import education_fee_penalty_rule
from . import account_move
from . import education_refund_request
from . import account_move_reversal
from . import education_enrollment
from . import education_transport_fee
