 # -*- coding: utf-8 -*-
{
    'name': 'Education Examination Management',
    'version': '19.0.1.0.0',
    'summary': 'Manage Examination Details',
    'category': 'Education',
    'sequence': -333,
    'author': 'Cybrosys Techno Solutions',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': 'https://www.cybrosys.com',
    'depends': ['base', 'mail','education_core'],
    'data': [
        'security/ir.model.access.csv',
        'security/education_exam_security.xml',
        'data/ir.sequence_data.xml',
        'data/exam_notification_template.xml',
        'data/exam_published_notification_template.xml',
        'data/cron.xml',
        'views/education_exam_views.xml',
        'views/education_exam_type_views.xml',
        'views/education_exam_valuation_views.xml',
        'views/education_exam_result_views.xml',
        'views/education_exam_revaluation_views.xml',
        'views/education_exam_revaluation_creation_views.xml',
        'views/education_exam_grade_views.xml',
        'wizard/education_exam_result_wizard_views.xml',
        # 'report/student_wise_report_template.xml',
        'report/ir_actions_report.xml',
        'report/student_exam_result_template.xml',
        'report/student_class_wise_report_template.xml',

    ],
    'license': 'AGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}